### ISSUE TITLE
Assets not inserting

### ISSUE THREAD

**Issue by CleverSource** [bobsh/BTK#8]
Can't insert the assets provided. Also an idea i'd give is better UI.

**Comment by kbarber** [comment]
I'm working on the UI now, converting everything to roact with roact-material ... just took me a while to figure this lua dev environment :-). Its heavily in my sights as you can see:

https://github.com/bobsh/BTK/projects/1

So apologies for the instability, consider this 'pre-alpha' but I'm happy to hear you've tried it.

I'll put this bug on the board, I know the problem, its just that I'm rewriting a large part of this code to be more stable and use good practices, please be patient.

**Comment by kbarber** [comment]
@CleverSource can you send me your console output in studio when this breaks?

**Comment by kbarber** [comment]
Actually, I'm going to drop this facility for now. I'm switching things around rapidly, and its not going useful now.
